name: 'Deploy'

on:
  # push:
    # tags:
      # - 'v*'
  workflow_dispatch:

jobs:
  deploy:
    environment:
      name: Production

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.0.0
      - run: echo 'Hello'
